server:
  port: 8086 # 端口

spring:
  application:
    name: ms-points # 应用名
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wx19930908
    url: jdbc:mysql://localhost:3306/dinners-social?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
  # Redis
  redis:
    port: 6379
    host: 192.168.160.130
    timeout: 3000
    password: 123123
    database: 3
  # Swagger
  swagger:
    base-package: com.imooc.points
    title: 慕课美食社交食客API接口文档


# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

service:
  name:
    ms-oauth-server: http://ms-oauth2-server/
    ms-dinners-server: http://ms-dinners/

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

logging:
  pattern:
    console: '%d{2100-01-01 13:14:00.666} [%thread] %-5level %logger{50} - %msg%n'